# Generated by Django 6.1.1 on 2026-09-13 16:27

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("legacy_image_path", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("product_code", models.CharField(max_length=50, unique=True)),
                (
                    "legacy_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency_code", models.CharField(default="BDT", max_length=3)),
                ("short_description", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("long_description", models.TextField(blank=True)),
                ("material", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=100)),
                ("finish", models.CharField(max_length=100)),
                ("dimensions", models.CharField(blank=True, max_length=255)),
                (
                    "occasions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "badges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("ask_about_availability", "Ask About Availability"),
                            ("made_to_order", "Made to Order"),
                        ],
                        default="ask_about_availability",
                        max_length=32,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_new_arrival", models.BooleanField(default=False)),
                ("is_best_seller", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "collections",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.collection"
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_path", models.CharField(blank=True, max_length=500)),
                ("cloudinary_public_id", models.CharField(blank=True, max_length=255)),
                ("secure_url", models.URLField(blank=True, max_length=500)),
                ("alt_text", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "provenance_status",
                    models.CharField(
                        choices=[
                            ("representative_demo", "Representative Demo"),
                            ("verified_product", "Verified Product"),
                            ("retired", "Retired"),
                        ],
                        default="representative_demo",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_published", "display_order"], name="product_pub_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_published", "display_order"],
                name="product_cat_pub_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="product_price_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_at_price__isnull", True),
                    ("compare_at_price__gte", models.F("price")),
                    _connector="OR",
                ),
                name="product_compare_price_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("display_order__gte", 0)),
                name="product_display_order_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                fields=("product", "sort_order"), name="product_image_sort_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="product_one_primary_image",
            ),
        ),
    ]
