# Generated by Django 6.1.1 on 2026-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cloudinary_public_id", ""), _negated=True),
                fields=("cloudinary_public_id",),
                name="product_image_cloudinary_id_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cloudinary_public_id", ""), ("secure_url", "")),
                    models.Q(
                        models.Q(("cloudinary_public_id", ""), _negated=True),
                        models.Q(("secure_url", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="product_image_cloudinary_metadata_pair",
            ),
        ),
    ]
